---
- name: Attach multiple policies to existing IAM user
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    iam_username: "{{ iam_username }}"
    policy_arns_list: "{{ policy_arns.split(',') }}"

  tasks:
    - name: Attach each policy to user
      amazon.aws.iam_policy_attachment:
        policy_arn: "{{ item }}"
        users:
          - "{{ iam_username }}"
        state: present
      loop: "{{ policy_arns_list }}"

