---
- name: Create IAM user
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    new_iam_username: "{{ new_iam_username | default('defaultuser') }}"
    policy_arns_list: "{{ policy_arns.split(',') }}"

  tasks:
    - name: Create new IAM user
      amazon.aws.iam_user:
        name: "{{ new_iam_username }}"
        state: present
      register: user_result

    - name: Attach each policy to new user
      amazon.aws.iam_policy_attachment:
        policy_arn: "{{ item }}"
        users:
          - "{{ new_iam_username }}"
        state: present
      loop: "{{ policy_arns_list }}"

    - name: Show result
      debug:
        var: user_result

