name: Create or Attach IAM Policies to User

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform: create_user or attach_policy'
        required: true
        default: 'create_user'
      iam_username:
        description: 'IAM username'
        required: true
        default: 'testuser-poc'
      policy_arns:
        description: 'Comma-separated list of policy ARNs'
        required: true
        default: 'arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible and AWS collection
        run: |
          pip install ansible boto3 botocore
          ansible-galaxy collection install -r requirements.yml

      - name: Run Ansible playbook based on action
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          if [ "${{ github.event.inputs.action }}" == "create_user" ]; then
            echo "Creating IAM user and attaching policies..."
            ansible-playbook create_iam_user.yml \
              --extra-vars "new_iam_username=${{ github.event.inputs.iam_username }} policy_arns='${{ github.event.inputs.policy_arns }}'"
          elif [ "${{ github.event.inputs.action }}" == "attach_policy" ]; then
            echo "Attaching policies to existing user..."
            ansible-playbook attach_policy.yml \
              --extra-vars "iam_username=${{ github.event.inputs.iam_username }} policy_arns='${{ github.event.inputs.policy_arns }}'"
          else
            echo "Unknown action: ${{ github.event.inputs.action }}"
            exit 1
          fi
