name: Create IAM User (and optionally attach policies)

on:
  workflow_dispatch:
    inputs:
      iam_username:
        description: 'IAM username to create'
        required: true
        default: 'testuser-poc'
      policy_arns:
        description: 'Comma-separated policy ARNs (optional)'
        required: false
        default: ''

jobs:
  create_user:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible and AWS collection
        run: |
          pip install ansible boto3 botocore
          ansible-galaxy collection install -r requirements.yml
      
      - name: List installed Ansible collections
        run: ansible-galaxy collection list

      - name: Run Ansible playbook
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          ansible-playbook create_iam_user.yml \
            --extra-vars "new_iam_username=${{ github.event.inputs.iam_username }} policy_arns='${{ github.event.inputs.policy_arns }}'"
